"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, BookHeart, ChartNoAxesCombined, HeartPulse, type LucideIcon } from "lucide-react";
import { motion } from "framer-motion";

const periods = [{ label: "Hari Ini", values: ["Membaik", "Stabil", "Perlu diperhatikan"], copy: "Hari ini menikmati waktu mengobrol di teras dan mengikuti aktivitas ringan sesuai kenyamanan." }, { label: "7 Hari", values: ["Stabil", "Membaik", "Stabil"], copy: "Catatan dalam tujuh hari membantu keluarga melihat rutinitas yang terasa nyaman." }, { label: "30 Hari", values: ["Teratur", "Stabil", "Dipantau"], copy: "Ringkasan bulanan memberi konteks untuk percakapan dan tindak lanjut keluarga." }] as const;
const labels = ["Energi", "Mood", "Mobilitas"];
const benefits: { icon: LucideIcon; text: string }[] = [
  { icon: HeartPulse, text: "Observasi yang mudah dipahami" },
  { icon: BookHeart, text: "Cerita kecil yang tidak terlewat" },
  { icon: ChartNoAxesCombined, text: "Perubahan terlihat dalam konteks" },
];

export default function RiwayatRangkulPreview() {
  const [active, setActive] = useState(0); const period = periods[active];
  return <section id="riwayat-rangkul" className="border-y border-blue-100 bg-[linear-gradient(135deg,#fff_0%,#dff1ff_50%,#fff_100%)] py-16 sm:py-20 lg:py-24"><div className="mx-auto grid max-w-[1220px] items-center gap-10 px-4 sm:px-6 lg:grid-cols-[minmax(0,.78fr)_minmax(0,1.22fr)] lg:gap-16 lg:px-8"><div><p className="text-xs font-extrabold tracking-[.14em] text-primary">RIWAYAT RANGKUL</p><h2 className="mt-3 max-w-xl font-heading text-3xl font-bold tracking-[-.035em] text-foreground sm:text-4xl">Bukan sekadar kunjungan. Lihat perubahan dari waktu ke waktu.</h2><p className="mt-5 max-w-xl text-base leading-7 text-muted-foreground">Observasi keseharian dan cerita singkat disimpan rapi agar keluarga tetap terhubung, tanpa menggantikan penilaian medis.</p><div className="mt-7 space-y-4">{benefits.map(({ icon: Icon, text }) => <div key={text} className="flex items-center gap-3 text-sm font-semibold text-foreground"><span className="flex size-9 items-center justify-center rounded-xl bg-white text-primary shadow-sm"><Icon className="size-4" aria-hidden="true" /></span>{text}</div>)}</div><Link href="/register?role=keluarga" className="mt-8 inline-flex min-h-11 items-center rounded-md bg-primary px-5 text-sm font-bold text-white hover:bg-[#083578] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2">Mulai pantau orang tersayang <ArrowRight className="ml-2 size-4" aria-hidden="true" /></Link></div>
    <motion.article initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .25 }} transition={{ duration: .55 }} className="rounded-[24px] border border-blue-200 bg-white p-5 shadow-[0_20px_56px_rgba(13,71,161,.14)] sm:p-7"><div className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-5"><div><p className="text-xs font-extrabold tracking-[.12em] text-primary">CONTOH TAMPILAN</p><h3 className="mt-2 font-heading text-xl font-bold text-foreground">Ibu Ratna</h3></div><p className="text-sm font-medium text-muted-foreground">27 Agustus 2026</p></div><div role="tablist" aria-label="Rentang contoh Riwayat Rangkul" className="mt-5 flex gap-2 rounded-xl bg-blue-50 p-1">{periods.map((item,index) => <button key={item.label} type="button" role="tab" aria-selected={active === index} onClick={() => setActive(index)} className={`min-h-11 flex-1 rounded-lg px-2 text-xs font-bold transition ${active === index ? "bg-white text-primary shadow-sm" : "text-muted-foreground hover:text-primary"}`}>{item.label}</button>)}</div><motion.div key={period.label} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: .2 }} className="mt-6 grid gap-3 sm:grid-cols-3">{labels.map((label, index) => <div key={label} className="rounded-xl border border-border bg-slate-50 p-3"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-2 text-sm font-bold text-foreground">{period.values[index]}</p><span className="mt-3 block h-1.5 rounded-full bg-[linear-gradient(90deg,#90CAF9,#0D47A1)]" /></div>)}</motion.div><div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><p className="text-xs font-extrabold tracking-[.12em] text-primary">CERITA HARI INI</p><p className="mt-2 text-sm leading-6 text-slate-700">“{period.copy}”</p></div><p className="mt-4 text-xs leading-5 text-muted-foreground">Contoh data untuk menunjukkan bentuk Riwayat Rangkul, bukan diagnosis atau rekomendasi medis.</p></motion.article>
  </div></section>;
}
